# Generated by Django 3.1.7 on 2021-04-24 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_code', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=60)),
                ('attribution', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_code', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('date_joined', models.DateField()),
                ('address1', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('zipcode', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_code', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('premium', models.CharField(max_length=60)),
                ('allocation', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriberID', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('motif_of_cancelation', models.CharField(max_length=60, null=True)),
                ('beneficiaryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
                ('service_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.service')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('subscription_type_code', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_type_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(max_length=60, null=True)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('address1', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('zipcode', models.CharField(max_length=60)),
                ('employer_name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('transferID', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_from', models.CharField(max_length=60)),
                ('transfer_to', models.CharField(max_length=60)),
                ('request_date', models.DateField()),
                ('transfer_date', models.DateField()),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscription_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinfo'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('MemberID', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('native_country', models.CharField(max_length=60)),
                ('citizenship', models.CharField(max_length=60)),
                ('is_delegate', models.BooleanField()),
                ('organization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.organization')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officerID', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('office_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.office')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
    ]
